# Generated by Django 5.0.6 on 2024-05-10 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("desc", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="female_actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("dob", models.DateField()),
                ("desc", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="male_actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("dob", models.DateField()),
                ("desc", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="multiplex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("no_of_screens", models.IntegerField()),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("1", "ahmedabad"),
                            ("2", "surat"),
                            ("3", "baroda"),
                            ("4", "bhavnagar"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "gujarat"), ("2", "maharashtra"), ("3", "goa")],
                        max_length=20,
                    ),
                ),
                ("website", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("desc", models.TextField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="moviedata.male_actor",
                    ),
                ),
                (
                    "actress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="moviedata.female_actor",
                    ),
                ),
                (
                    "movie_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="moviedata.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="shows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("showtime", models.DateTimeField()),
                ("seats", models.IntegerField()),
                ("ticket_price", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("1", "2-D"), ("2", "3-D")], max_length=20
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("1", "english"), ("2", "gujrati"), ("3", "hindi")],
                        max_length=20,
                    ),
                ),
                (
                    "movie_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="moviedata.movie",
                    ),
                ),
                (
                    "multiplex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="moviedata.multiplex",
                    ),
                ),
            ],
        ),
    ]
